name: HMCTS Management Information ADF Self Hosted Integration Runtime Image
trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  applicationName: 'mi-adf-integration-runtime'
  azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-PROD'
  azureContainerRegistry: 'sdshmctspublic.azurecr.io'
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}: 
    deployTarget: prod
  ${{ if not(eq(variables['Build.SourceBranchName'], 'main')) }}: 
    deployTarget: dev

stages:
  - stage: BuildAndPush
    jobs:
      - job: BuildAndPush
        steps:
          - bash: |
              repo_sha=$(git rev-parse --verify HEAD)
              docker_image_tag_sha=${repo_sha:0:7}
              echo "##vso[task.setvariable variable=DOCKER_TAG;isOutput=true]${docker_image_tag_sha}"
            displayName: 'Get Docker Tag'
            name: 'getDockerTag'
          - task: Docker@1
            displayName: 'Docker Login'
            inputs:
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureContainerRegistry: $(azureContainerRegistry)
              command: login
          - task: Docker@1
            displayName: 'Build Docker Image'
            inputs:
              imageName: '$(azureContainerRegistry)/$(applicationName):$(deployTarget)-$(getDockerTag.DOCKER_TAG)'
              command: build
              Dockerfile: ./Dockerfile
          - task: Docker@1
            displayName: 'Push Docker Image'
            inputs:
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureContainerRegistry: $(azureContainerRegistry)
              command: push
              imageName: '$(applicationName):$(deployTarget)-$(getDockerTag.DOCKER_TAG)'
          - task: Docker@1
            displayName: 'Docker Logout'
            inputs:
              command: logout