name: HMCTS Management Information ADF Self Hosted Integration Runtime Image
trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  applicationName: 'mi-adf-integration-runtime'
  azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-PROD'
  azureContainerRegistry: 'sdshmctspublic.azurecr.io'

stages:
  - stage: BuildAndPush
    jobs:
      - job: BuildAndPush
        steps:
          - bash: |
              buildDate=$(date +"%Y-%m-%d %H:%M:%S")
              echo "##vso[task.setvariable variable=Build_DT;isOutput=true]${buildDate}"
            displayName: 'Get Build Date and Time'
            name: 'getBuildDateTime'
          - task: Docker@2
            displayName: 'Docker Login'
            inputs:
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureContainerRegistry: $(azureContainerRegistry)
              command: login
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              repository: '$(azureContainerRegistry)/$(applicationName):$(getBuildDateTime.Build_DT)'
              command: build
              Dockerfile: ./Dockerfile
          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureContainerRegistry: $(azureContainerRegistry)
              command: push
              imageName: '$(applicationName):$(getBuildDateTime.Build_DT)'
          - task: Docker@2
            displayName: 'Docker Logout'
            inputs:
              command: logout