name: Build Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}:$(date +%s)

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        run: docker build --tag $DOCKER_IMAGE .

      - name: Docker push
        run: docker push  $DOCKER_IMAGE

